version: '3.8'

services:
  # Frontend Development
  frontend-shell:
    build:
      context: .
      dockerfile: ./apps/frontend/shell/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api-gateway

  # Backend Services
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/backend/api-gateway/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - ENV=development
      - PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:8081
      - BLOG_SERVICE_URL=http://blog-service:8082
      - USER_SERVICE_URL=http://user-service:8083
    depends_on:
      - auth-service
      - blog-service
      - user-service

  auth-service:
    build:
      context: .
      dockerfile: ./apps/backend/auth-service/Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    environment:
      - ENV=development
      - PORT=8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_db
      - JWT_SECRET=dev_secret_key
    depends_on:
      - postgres

  blog-service:
    build:
      context: .
      dockerfile: ./apps/backend/blog-service/Dockerfile.dev
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
    environment:
      - ENV=development
      - PORT=8082
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=blog_db
    depends_on:
      - postgres

  user-service:
    build:
      context: .
      dockerfile: ./apps/backend/user-service/Dockerfile.dev
    ports:
      - "8083:8083"
    volumes:
      - ./:/app
    environment:
      - ENV=development
      - PORT=8083
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_db
    depends_on:
      - postgres

  # Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth_db,blog_db,user_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh

  # Development Tools
  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
